version: '31.0'

services:
  proxy:
    build: ./src
    command: bash -c "./run.sh"
    volumes:
      - type: bind
        source: ./var
        target: /var/log/erss
    ports:
      - "12345:12345"